### PR TITLE
Add Japanese language file

### PR DESCRIPTION
**Pull request by tao-s**

### CODE REVIEW

**Comment by brucewyne** [comment]
You are super awesome! Thanks. This is a great contribution and I really appreciate it.

**Comment by tao-s** [comment]
Your works is great.
I want to show to Japanese people this add-on.
Please update this on market place.

**Comment by brucewyne** [comment]
Will do. We need to wrap up flexible shipping methods, and then we'll push out the newest release to the marketplace.

**Comment by brucewyne** [comment]
@tao-s Could you go over this again? We've made some edits/additions and want to make sure it's still complete.

**Comment by tao-s** [comment]
@brucewyne Thank you.

**Pull request merged**
